version: '3.8'

services:
  authservice:
    image: authservice
    build:
      context: ./authservice
      dockerfile: Dockerfile
    ports:
      - "7283:7283"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

  productservice:
    image: productservice
    build:
      context: ./productservice
      dockerfile: Dockerfile
    ports:
      - "7099:7099"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

  orderservice:
    image: orderservice
    build:
      context: ./orderservice
      dockerfile: Dockerfile
    ports:
      - "7155:7155"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network
networks:
  app-network:
    driver: bridge