name: Dotnet build CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'

    - name: Build authservice
      run: |
        cd src/authservice
        dotnet build --configuration Release

    - name: Build productservice
      run: |
        cd src/productservice
        dotnet build --configuration Release

    - name: Build orderservice
      run: |
        cd src/orderservice
        dotnet build --configuration Release

    - name: Build authservice.test
      run: |
        cd tests/authservice.test
        dotnet build --configuration Release

    - name: Run authservice tests
      run: |
        cd tests/authservice.test
        dotnet test --configuration Release --no-build --verbosity normal
